# Generated by Django 4.0.3 on 2024-05-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.PositiveIntegerField()),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('middle_initial', models.CharField(max_length=2)),
                ('course_name', models.CharField(max_length=250)),
                ('year_level', models.PositiveSmallIntegerField()),
                ('subjects', models.PositiveSmallIntegerField()),
                ('image', models.TextField()),
            ],
        ),
    ]
